- ros_topic_name: "/tf"
  gz_topic_name: "model/ingenuity_model/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "/joint_state"
  gz_topic_name: "/world/ingenuity_world/model/ingenuity_model/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "/wrench/blade_1"
  gz_topic_name: "/wrench/ingenuity_model/blade_1"
  ros_type_name: "geometry_msgs/msg/Wrench" 
  gz_type_name: "gz.msgs.Wrench"
  direction: GZ_TO_ROS

- ros_topic_name: "/wrench/blade_2"
  gz_topic_name: "/wrench/ingenuity_model/blade_2"
  ros_type_name: "geometry_msgs/msg/Wrench" 
  gz_type_name: "gz.msgs.Wrench"
  direction: GZ_TO_ROS

- ros_topic_name: "/wrench/blade_3"
  gz_topic_name: "/wrench/ingenuity_model/blade_3"
  ros_type_name: "geometry_msgs/msg/Wrench" 
  gz_type_name: "gz.msgs.Wrench"
  direction: GZ_TO_ROS

- ros_topic_name: "/wrench/blade_4"
  gz_topic_name: "/wrench/ingenuity_model/blade_4"
  ros_type_name: "geometry_msgs/msg/Wrench" 
  gz_type_name: "gz.msgs.Wrench"
  direction: GZ_TO_ROS

- ros_topic_name: "/camera"
  gz_topic_name: "/camera"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS


- ros_topic_name: "/ingenuity_battery/state"
  gz_topic_name: "/model/ingenuity_model/battery/ingenuity_battery/state"
  ros_type_name: "sensor_msgs/msg/BatteryState"
  gz_type_name: "gz.msgs.BatteryState"
  direction: GZ_TO_ROS

# Publish the desired altitude:
# e.g. 10-25 m
- ros_topic_name: "/desired_altitude"
  gz_topic_name: "/desired_altitude"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

#  Publish the angle of attack collective control:
#  between -0.0349066 and 0.139626 radians(2 to 8 degrees)
- ros_topic_name: "/angle_of_attack"
  gz_topic_name: "/angle_of_attack"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Publish the lateral cyclic control:
# between -0.00001 to 0.00001
- ros_topic_name: "/alpha_c"
  gz_topic_name: "/alpha_c"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ


# Publish the longitudinal cyclic control:
# between -0.00001 to 0.00001
- ros_topic_name: "/alpha_s"
  gz_topic_name: "/alpha_s"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
