FROM ros:jazzy-ros-core-noble

ARG DEBIAN_FRONTEND=noninteractive

ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
ENV ROS_DISTRO=jazzy
ENV USERNAME=spaceros-user
ENV HOME=/home/spaceros-user
ENV GZ_VERSION=harmonic

# Install dependencies
RUN apt update && \
    apt install -y \
      ros-${ROS_DISTRO}-rmw-cyclonedds-cpp \
      wget \
      curl \
    && apt clean  \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg\
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" | tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null

# Install Gazebo
RUN apt-get update -qq && \
    apt-get install -y \
      gz-${GZ_VERSION} \
      build-essential\
      ros-${ROS_DISTRO}-rcl-interfaces\
      ros-${ROS_DISTRO}-rclcpp\
      ros-${ROS_DISTRO}-builtin-interfaces\
      ros-${ROS_DISTRO}-ros-gz\
      ros-${ROS_DISTRO}-sdformat-urdf\
      ros-${ROS_DISTRO}-vision-msgs\
      ros-${ROS_DISTRO}-actuator-msgs\
      ros-${ROS_DISTRO}-image-transport\
      ros-${ROS_DISTRO}-xacro\
    && rm -rf /var/lib/apt/lists/*


# Install Rviz2
RUN apt-get update -qq && \
    apt-get install -y \
      ros-${ROS_DISTRO}-rviz2 \
      ros-${ROS_DISTRO}-moveit-ros-visualization \
      ros-${ROS_DISTRO}-nav2-rviz-plugins \
    && rm -rf /var/lib/apt/lists/*


# Install Leo packages
RUN apt-get update -qq && \
    apt-get install -y \
      ros-${ROS_DISTRO}-leo-gz-plugins\
      ros-${ROS_DISTRO}-leo-teleop \
    && rm -rf /var/lib/apt/lists/*

# Demo package
RUN mkdir -p ${HOME}/lunar_terrain_ws/src
WORKDIR ${HOME}/lunar_terrain_ws/src
COPY ./lunar_sun_gz_plugin ./lunar_sun_gz_plugin
COPY ./lunar_terrain_gz_bringup ./lunar_terrain_gz_bringup
COPY ./lunar_terrain_gz_worlds ./lunar_terrain_gz_worlds
COPY .defaults.yaml ${HOME}/lunar_terrain_ws/.defaults.yaml

RUN apt update \
    && apt install -y python3-rosdep python3-colcon-common-extensions \
    && apt clean \
    && rm -rf /var/lib/apt/lists/* \
    && rosdep init \
    && rosdep update

RUN . /opt/ros/${ROS_DISTRO}/setup.sh && \
    cd ${HOME}/lunar_terrain_ws && \
    apt update && \
    rosdep install --from-paths src --ignore-src -r -y && \
    colcon build

WORKDIR ${HOME}/lunar_terrain_ws

RUN apt update && \
    apt install -y \
      ros-${ROS_DISTRO}-ros-gz
RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> ${HOME}/.bashrc
RUN echo "source ${HOME}/lunar_terrain_ws/install/setup.bash" >> ${HOME}/.bashrc

CMD gz sim
